version: "3.8"
services:
  server:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - database
  database:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: u
      POSTGRES_PASSWORD: p
    ports:
      - "5432:5432"